### ISSUE TITLE
Accessing Stored File

### ISSUE THREAD

**Issue by rmaspero** [shrinerb/shrine-memory#1]
I'm not sure if I should be able to do this with the gem anyway. I am using Shrine memory for my test environment. I am trying to write a feature spec to check a process in which a user uploads a CSV, matches up the files headers and it processes it. I've setup shrine memory in the initialiser as below:

```
if Rails.env.test?
  require 'shrine/storage/memory'
  Shrine.storages = {
    cache: Shrine::Storage::Memory.new,
    store: Shrine::Storage::Memory.new,
  }
else
```

I am then adding a csv file in my factory which I want to use later in my controller. I run the FactoryGirl factory in my spec and it all seems to work fine. When inspecting it I get back a url of it in memory. However when I visit the page where I am matching up the headers of the csv file it fails. It says it is unable to find the file in memory. As I need to open the file to find out what the headers are.

Should/would the file created in the factory actually be accessible, if it is meant to be what am I doing wrong? If not is their a way I can force the model to point to a file I store somewhere else?

**Comment by janko** [comment]
The URL that the memory storage returns is a fake URL. The uploaded files are not accessible via a URL because they're just stored in memory of a specific Ruby process.

What do you mean by "file headers"? If you're normally uploading to S3, any request headers that are sent are only specific to the S3 storage, they aren't being created when you use another storage. If you want to test S3 logic you can use [Minio](https://minio.io), here is a short guide: https://github.com/janko-m/shrine/blob/master/doc/testing.md#direct-s3-uploads.
